name: tele_book
version: 2.0.7+1
publish_to: none
description: Simple way that download the telegraph Book.
environment: 
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.7.3
  flutter: 
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.1
  html: ^0.15.0
  dio: ^5.4.0
  flutter_launcher_icons: ^0.14.3
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  tdesign_flutter: ^0.2.7
  background_downloader: ^9.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  archive: ^4.0.7
  file_picker: ^10.3.8
  permission_handler: ^12.0.1
  http: ^1.3.0
  wakelock_plus: ^1.2.10
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  pdf_to_image_converter: ^0.0.5
  open_filex: ^4.4.0
  share_plus: ^12.0.1
  dk_util:
    path: /home/dorkytiger/IdeaProjects/dk_util  # 绝对路径

dev_dependencies: 
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true
